### ISSUE TITLE
[4.0] SiteTree does not filter BlogPosts that are displayed in the GridField

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-lumberjack#50]
![image](https://cloud.githubusercontent.com/assets/5170590/22325119/9f5b2aac-e411-11e6-8fc3-cdcfaba8419a.png)

`BlogPost` has `private static $show_in_sitetree = false`, but they are showing in the SiteTree.

**Comment by robbieaverill** [comment]
Quick check: In 3.5, on page load the tree view is loaded via XHR - in 4.0 it's not, so `Lumberjack::shouldFilter` returns false because the action is "edit", not "listview", etc.

**Comment by axllent** [comment]
I *believe* the `Lumberjack::shouldFilter` should be detecting a "show" `getAction()` - or rather when I played around with the source that seemed to work. There's probably more to it that that I guess.

Is anything being done to get this functionality working again for SS4 as the bug has been open since January and it is a core feature of the module?

**Comment by robbieaverill** [comment]
I'm sure it'll get looked at before SS4 is stable :-)

**Comment by robbieaverill** [comment]
Fixed in #57

**Comment by Firesphere** [comment]
I believe this is now resolved with the acceptance of #57
