### ISSUE TITLE
Manual Sorting

### ISSUE THREAD

**Issue by pxwee5** [silverstripe/silverstripe-lumberjack#66]
Using Lumberjack, there's no way to manually sort the posts that inputs into the "sort" database field. We lost the functionality that we had in the sitetree. 

Is there a way to make the GridField a sortable gridfield ?

**Comment by robbieaverill** [comment]
@pxwee5 you could install symbiote/silverstripe-gridfieldextensions and add the GridFieldOrderableRows component if you wanted to

**Comment by robbieaverill** [comment]
@pxwee5 the easiest way I found to do this is to overload the GridFieldConfig class used in lumberjack (or blog if that's what you're using), and add the component there:

```php
class MyLumberjackConfig extends GridFieldConfig_BlogPost
{
    public function __construct($itemsPerPage = null)
    {
        parent::__construct($itemsPerPage);
        $this->addComponent(new GridFieldOrderableRows());
    }
}
```

You can overload with YAML:

```yaml
Injector:
  GridFieldConfig_BlogPost:
    class: MyLumberjackConfig
```

If you aren't using the blog module, but lumberjack directly, then use `GridFieldConfig_Lumberjack` instead of `GridFieldConfig_BlogPost`.

Hope this helps!

**Comment by jinjie** [comment]
It's been 4 years+ not sure if there's an easier way to do this. Just in case if anyone are looking for the same, a better way is to add this to the extending page:

```
public function getLumberjackGridFieldConfig()
{
    $gridFieldConfig = GridFieldConfig_Lumberjack::create();

    $gridFieldConfig->addComponent(new GridFieldOrderableRows());

    return $gridFieldConfig;
}
```
